services:
  - type: web
    runtime: static
    name: mariners-lms-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build

    routes:
      - type: rewrite
        source: /*
        destination: /index.html